name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: yandex-cloud/ui-release-action@main
        with:
          github-token: ${{ secrets.YC_UI_BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.YC_UI_BOT_NPM_TOKEN }}
          node-version: 14